name: Housekeeping Workflow Runs

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
          KEEP_RUNS: 2
        run: |
          # Function to get workflow runs for a specific workflow
          get_workflow_runs() {
            local workflow_id=$1
            local branch=$2
            gh api \
              -H "Accept: application/vnd.github+json" \
              "/repos/$REPO/actions/workflows/$workflow_id/runs?branch=$branch&per_page=100" \
              --jq '.workflow_runs[] | {id: .id, created_at: .created_at, workflow_name: .name, branch: .head_branch}'
          }

          # Get all workflows
          workflows=$(gh api "/repos/$REPO/actions/workflows" --jq '.workflows[] | {id: .id, name: .name}')

          # Get all branches
          branches=$(gh api "/repos/$REPO/branches" --jq '.[].name')

          echo "Processing workflows and branches..."

          # Process each workflow and branch combination
          echo "$workflows" | while read -r workflow; do
            workflow_id=$(echo "$workflow" | jq -r '.id')
            workflow_name=$(echo "$workflow" | jq -r '.name')
            
            echo "Processing workflow: $workflow_name (ID: $workflow_id)"
            
            echo "$branches" | while read -r branch; do
              if [ ! -z "$branch" ]; then
                echo "Processing branch: $branch"
                
                # Get runs for this workflow and branch
                runs=$(get_workflow_runs "$workflow_id" "$branch")
                
                if [ ! -z "$runs" ]; then
                  # Sort runs by creation date and ski