name: Terraform Destroy PROD

on:
  workflow_dispatch:

jobs:
  destroy-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login - PROD
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.QA_CLIENT_ID }}","clientSecret":"${{ secrets.QA_CLIENT_SECRET }}","subscriptionId":"${{ secrets.QA_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.QA_TENANT_ID }}"}'


      - name: Destroy PROD
        working-directory: infrastructure/terraform/1-infrastructure
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.PROD_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.PROD_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.PROD_CLIENT_SECRET }}
        run: |
          terraform init  \
          -backend-config="resource_group_name=revue-tfstate-rg" \
          -backend-config="storage_account_name=revuetfstatecya4cd8g" \
          -backend-config="container_name=tfstate-prod" \
          -backend-config="key=terraform.tfstate"
          terraform workspace select prod
          terraform destroy -var-file="prod.tfvars" -auto-approve