name: Terraform Destroy QA

on:
  workflow_dispatch:

jobs:
  destroy-qa:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login - QA
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.QA_CLIENT_ID }}","clientSecret":"${{ secrets.QA_CLIENT_SECRET }}","subscriptionId":"${{ secrets.QA_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.QA_TENANT_ID }}"}'


      - name: Destroy QA
        working-directory: infrastructure/terraform/1-infrastructure
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.QA_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.QA_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.QA_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.QA_CLIENT_SECRET }}
          TF_VAR_github_username: ${{ secrets.GH_USER_NAME }}
          TF_VAR_github_pat: ${{ secrets.GH_PAT }}
        run: |
          terraform init  \
          -backend-config="resource_group_name=revue-tfstate-rg" \
          -backend-config="storage_account_name=revuetfstateeu6ltgbm" \
          -backend-config="container_name=tfstate-qa" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="subscription_id=${{ secrets.QA_SUBSCRIPTION_ID }}" \
          -backend-config="client_id=${{ secrets.QA_CLIENT_ID }}" \
          -backend-config="client_secret=${{ secrets.QA_CLIENT_SECRET }}" \
          -backend-config="tenant_id=${{ secrets.QA_TENANT_ID }}"
          terraform destroy  \
          -var="github_username=${{ secrets.GH_USER_NAME }}" \
          -var="github_pat=${{ secrets.GH_PAT }}" \
          -var="github_email=ravjot28@gmail.com" \
          -var-file="environments/qa.tfvars" -auto-approve