name: Terraform Destroy PROD

on:
  workflow_dispatch:

jobs:
  destroy-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Destroy PROD
        working-directory: infrastructure/terraform/1-infrastructure
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.PROD_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.PROD_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.PROD_CLIENT_SECRET }}
        run: |
          terraform init
          terraform workspace select prod
          terraform destroy -var-file="prod.tfvars" -auto-approve